python3 ../../main_linear.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_folder /data/datasets \
    --train_dir imagenet-100/train \
    --val_dir imagenet-100/val \
    --max_epochs 100 \
    --gpus 0, \
    --distributed_backend ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 3.0 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 10 \
    --dali \
    --name swav-linear-eval \
    --pretrained_feature_extractor /home/efini/projects/solo-learn/bash_files/pretrain/wandb/run-20210603_115635-3qkpyyub/files/contrastive_learning/3qkpyyub/checkpoints/epoch\=494-step\=244529.ckpt \
    --project contrastive_learning \
    --entity unitn-mhug \
    --wandb
