python3 ../main_contrastive.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_folder /data/datasets/ \
    --train_dir imagenet-100/train \
    --val_dir imagenet-100/val \
    --epochs 100 \
    --optimizer sgd --lars \
    --scheduler warmup_cosine \
    --lr 1.0 \
    --classifier_lr 0.1 \
    --weight_decay 1e-6 \
    --batch_size 128 \
    --gpus 0 1 \
    --num_workers 8 \
    --hidden_dim 2048 \
    --dali \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --asymmetric_augmentations \
    --name byol \
    --project contrastive_learning \
    --wandb \
    byol \
    --encoding_dim 128 \
    --hidden_dim 2048 \
    --pred_hidden_dim 512 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0
