srun python main_pretrain.py \
    --dataset $1 \
    --encoder resnet18 \
    --data_dir datasets \
    --max_epochs 1000 \
    --gpus 0,1,2,3 \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --accelerator ddp \
    --sync_batchnorm \
    --lr 0.05 \
    --classifier_lr 0.1 \
    --weight_decay 1e-4 \
    --batch_size 256 \
    --num_workers 5 \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.2 \
    --hue 0.1 \
    --gaussian_prob 0.0 0.0 \
    --solarization_prob 0.0 0.2 \
    --name mean_shift-2-$1 \
    --project solo-learn \
    --entity a-patnala \
    --wandb \
    --method mean_shift \
    --output_dim 512 \
    --proj_hidden_dim 4096 \
    --pred_hidden_dim 4096 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 1.0 \
    --momentum_classifier \
    --num_neighbors 5 \
    --queue_size 409600 \
    --auto_umap \
    --auto_umap_frequency 50
