python3 ../../../main_linear.py \
    --dataset imagenet \
    --backbone resnet50 \
    --data_dir /data/datasets \
    --train_dir imagenet/train \
    --val_dir imagenet/val \
    --max_epochs 100 \
    --gpus 0 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --lr 0.3 \
    --scheduler cosine \
    --weight_decay 1e-5 \
    --batch_size 256 \
    --num_workers 10 \
    --dali \
    --pretrained_feature_extractor PATH \
    --name barlow-resnet50-imagenet-linear-eval \
    --entity unitn-mhug \
    --project solo-learn \
    --wandb
