python3 ../../../main_linear.py \
    --dataset imagenet \
    --encoder resnet50 \
    --data_dir /datasets \
    --train_dir ILSVRC2012/train \
    --val_dir ILSVRC2012/val \
    --max_epochs 100 \
    --gpus 0 \
    --accelerator ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --scheduler step \
    --lr 0.1 \
    --lr_decay_steps 60 80 \
    --weight_decay 0 \
    --batch_size 256 \
    --num_workers 10 \
    --dali \
    --pretrained_feature_extractor PATH \
    --name byol-resnet50-imagenet-linear-eval \
    --entity unitn-mhug \
    --project solo-learn \
    --wandb
