python3 main_linear.py \
    --dataset imagenet100 \
    --backbone vit_base \
    --train_data_path $1/train.h5 \
    --val_data_path $1/val.h5 \
    --max_epochs 100 \
    --devices 0,1,2,3,4,5,6,7 \
    --accelerator gpu \
    --strategy ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer adamw \
    --scheduler warmup_cosine \
    --warmup_epochs 0 \
    --lr 5e-4 \
    --weight_decay 0.05 \
    --batch_size 64 \
    --num_workers 10 \
    --data_format h5 \
    --name mae-finetune-eval-imagenet100 \
    --pretrained_feature_extractor $2 \
    --project solo-learn \
    --entity unitn-mhug \
    --save_checkpoint \
    --wandb \
    --pretrain_method mae \
    --label_smoothing 0.1 \
    --layer_decay 0.75 \
    --drop_path 0.1 \
    --mixup 0.8 \
    --cutmix 1.0 \
    --finetune
