python3 ../../../main_contrastive.py \
    --dataset imagenet100 \
    --encoder resnet18 \
    --data_dir /data/datasets \
    --train_dir imagenet-100/train \
    --val_dir imagenet-100/val \
    --max_epochs 400 \
    --gpus 0,1 \
    --distributed_backend ddp \
    --sync_batchnorm \
    --precision 16 \
    --optimizer sgd \
    --scheduler cosine \
    --lr 0.06 \
    --classifier_lr 0.1 \
    --weight_decay 1e-4 \
    --batch_size 128 \
    --num_workers 8 \
    --dali \
    --brightness 0.4 \
    --contrast 0.4 \
    --saturation 0.4 \
    --hue 0.1 \
    --min_scale_crop 0.2 \
    --name mocov2plus-400ep-imagenet100 \
    --project solo-learn \
    --entity unitn-mhug \
    --wandb \
    --method mocov2plus \
    --proj_hidden_dim 512 \
    --queue_size 65536 \
    --temperature 0.2 \
    --base_tau_momentum 0.999 \
    --final_tau_momentum 0.999
